### PR TITLE
Check the file existence before deleting

### PR DESCRIPTION
**Pull request by bogdal**
In cases when we use `Google storage` for example,  we don't want to delete the files twice, what in consequence throws error.

### CODE REVIEW

**Comment by patrys** [comment]
Why do we delete files twice? This sounds like a bug we should fix first.

**Comment by bogdal** [comment]
This signal assumes that the file still exists physically, however using external storage we don't have them here.

**Comment by patrys** [comment]
How does the file cease to exist without us deleting it explicitly?

**Comment by bogdal** [comment]
I have double checked this signals and it looks like both `ProductImage` and `Image` call `delete_image_files` signal. First of them deletes file.
In my opinion `Image` model should be abstract and `ProductImage` should inherit from it.

Btw. Standard Django storage (inside `delete` method) checks the existence of the file first and then deletes it, hence for local storage this works as a charm.

**Comment by bogdal** [comment]
@patrys In addition I added `IMAGE DELETE ATTACHED FILE` parameter. We can decide whether we want to delete files from the storage or not.

**Comment by patrys** [comment]
I think IMAGE_AUTO_DELETE would be easier to parse.

**Comment by bogdal** [comment]
@patrys Could you review and merge this PR?

**Pull request merged**
